### ISSUE TITLE
Housekeeping: List of miscellaneous todo fixes

### ISSUE THREAD

**Issue by mattmcfad** [mattmcfad/VISA-Reader-TWO#11]
Add spinner to upload button instead of span #10 
- [x] Import Papaparse module instead of using global window object... #10 
- [ ] Import react-select in css/postcss
- [ ] move `index.html` template into src or server
- [ ] Remove dist folder completely
- [ ] Go stateless
